# Generated by Django 2.2.6 on 2019-10-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='htmlpost',
            options={'verbose_name': 'HTML post', 'verbose_name_plural': 'HTML posts'},
        ),
        migrations.AlterField(
            model_name='htmlpost',
            name='template_name',
            field=models.CharField(max_length=255),
        ),
    ]
