# Generated by Django 2.2.6 on 2019-10-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191007_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='preview',
            field=models.CharField(default='crunchem', max_length=240),
            preserve_default=False,
        ),
    ]
