# Generated by Django 2.2.6 on 2019-10-08 20:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191008_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('text', ckeditor.fields.RichTextField()),
                ('preview', models.CharField(max_length=240)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
