# Generated by Django 2.2.6 on 2019-10-23 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191021_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlpost',
            name='author',
            field=models.CharField(default='ryanmanny', max_length=120, verbose_name='written by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='htmlpost',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='ryanmanny', max_length=120, verbose_name='written by'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
