# Generated by Django 2.2.6 on 2019-10-09 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.BlogPost'),
        ),
    ]
