# Generated by Django 2.2.6 on 2019-10-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191023_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='htmlpost',
            old_name='published_on',
            new_name='published_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='published_on',
            new_name='published_at',
        ),
    ]
