# Generated by Django 2.2.6 on 2019-10-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191023_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlpost',
            name='preview',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.CharField(max_length=1200),
        ),
    ]
