# Generated by Django 2.2.6 on 2020-03-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191024_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htmlpost',
            name='category',
            field=models.CharField(max_length=80),
        ),
    ]
