# Generated by Django 2.2.6 on 2020-06-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_attachedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachedimage',
            name='name',
            field=models.CharField(default='honk', max_length=80),
            preserve_default=False,
        ),
    ]
