# Generated by Django 2.2.6 on 2019-10-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CribbagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('preview', models.CharField(max_length=240)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
